blank_issues_enabled: false
contact_links:
  - name: Tasks (Features) 🚀
    url: https://github.com/PROJECT-PIPLUP/lounas/issues/new?assignees=&labels=&template=task-feature.md&title=%5BFeature%5D%3A+
    about: For TEAM PIPLUP 🐧
